version: "3.9"
services:
  db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_DB=propertypicker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - db:db
    environment:
      - POSTGRES_NAME=propertypicker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_started
volumes:
  postgres_data:
