# Generated by Django 5.0.4 on 2024-04-26 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_latlong_location_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField()),
                ('phone', models.CharField(null=True)),
                ('position', models.CharField()),
                ('zone', models.CharField(null=True)),
                ('condition', models.CharField(choices=[('new_house', 'New House'), ('old_house', 'Old House'), ('land', 'Land'), ('land_with_construction', 'Land With Construction'), ('apartment', 'Apartment')], default='old_house')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('avenue', 'Avenue'), ('gated_community', 'Gated Community'), ('asphalt', 'Asphalt')]), blank=True, default=list, size=None)),
                ('m2', models.DecimalField(decimal_places=2, max_digits=20)),
                ('built_m2', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_per_built_m2', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('meters_in_front', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
