# Generated by Django 5.0.4 on 2024-04-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
