# Generated by Django 5.0.4 on 2024-04-26 21:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_built_m2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.CharField(verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='location',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='m² construidos'),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('new_house', 'Casa Nueva'), ('old_house', 'Casa Vieja'), ('land', 'Terreno'), ('land_with_construction', 'Terreno con Construcción'), ('apartment', 'Departamento')], default='old_house', verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='property',
            name='m2',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='m²'),
        ),
        migrations.AlterField(
            model_name='property',
            name='meters_in_front',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Metros de frente'),
        ),
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='property',
            name='position',
            field=models.CharField(verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_built_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Precio por m² construido'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Precio por m²'),
        ),
        migrations.AlterField(
            model_name='property',
            name='reference',
            field=models.CharField(verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('avenue', 'Avenida'), ('gated_community', 'Condominio Cerrado'), ('asphalt', 'Asfalto')]), blank=True, default=list, size=None, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zone',
            field=models.CharField(blank=True, null=True, verbose_name='Zona'),
        ),
    ]
