# Generated by Django 5.0.4 on 2024-04-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_location_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.JSONField(verbose_name='Direction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='properties.location')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='properties.property')),
            ],
        ),
    ]
