# Generated by Django 5.0.4 on 2024-04-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_location_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='direction',
        ),
        migrations.AddField(
            model_name='direction',
            name='route_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Direction'),
        ),
    ]
