# Generated by Django 5.0.4 on 2024-04-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_zone"),
    ]

    operations = [
        migrations.RunSQL("UPDATE properties_property SET zone = null"),
        migrations.AlterField(
            model_name="property",
            name="zone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="properties",
                to="properties.zone",
                verbose_name="Zona",
            ),
        ),
    ]
